### ISSUE TITLE
Problem with SIC

### ISSUE THREAD

**Issue by saheethas** [aaoiki/sic#1]
Hi,

I've tried installing this Password Manager tool. But it doesn't seem to work as expected.
-----------------------------------------------------------------------------------------
]# ./sic add user@gmail.com test123
Enter GPG Passphrase for (default key): 

[root@centos ~]# ./sic ls
Enter GPG Passphrase for (default key): 

KEY VALUE
-----------------------------------------------------------------------------------------
Unable to list the added entries.

Please see my OS details below:
-----------------------------------------------------------------------------------------

[root@centos ~]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@centos ~]# uname -a
Linux centos 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------------------------------

Can you please advise on how to solve this problem?

**Comment by aonemd** [comment]
Hello @saheethas! You need to have a GPG key to use `sic`. I added a check on that before prompting the user for the passphrase. Thanks for opening the issue.
